displayName=2DScape
author=KierenBoal
description=RuneScape Classic inspired graphics
tags=2d,2dscape,classic,sprite,doom,rsc
version=1.0.0
plugins=com.kierenboal.npcsnap.NpcSnapPlugin
build=standard
